GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/6a37019cfb2eaa5b5db3a805

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0cmF3YmVycnlqYW0yOTM2IiwiaWQiOiI2YTM2ZmZlYTFlNTQxZTk0MzQxZGNiZDUiLCJpYXQiOjE3ODIwMzMwMTJ9.VSP9y6YCE_oSo0BJktvdL1OSKS5gwTGKAzLDWubyRd0

{
    "title":"PyTorch is dying for real again",
    "url":"https://pytorch.org",
    "likes":16,
    "userId": "6a36ffea1e541e94341dcbd5"
}

###

PUT http://localhost:3003/api/blogs/6a37019cfb2eaa5b5db3a805
Content-Type: application/json

{
    "title": "PyTorch is dying but edited",
    "url": "https://pytorch.org/nn",
    "likes":20
}

###

DELETE  http://localhost:3003/api/blogs/6a3700dd84eeaf052c820d43