GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/6a37019cfb2eaa5b5db3a805

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"PyTorch is dying again",
    "url":"https://pytorch.org",
    "likes":16,
    "userId": "6a36ffea1e541e94341dcbd5"
}

###

PUT http://localhost:3003/api/blogs/6a37019cfb2eaa5b5db3a805
Content-Type: application/json

{
    "title": "PyTorch is dying but edited",
    "url": "https://pytorch.org/nn",
    "likes":20
}

###

DELETE  http://localhost:3003/api/blogs/6a3700dd84eeaf052c820d43